spring:
  application:
    name: favorite-products
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      enable: true
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/FavoriteProducts
          jwk-set-uri: http://localhost:8180/auth/realms/FavoriteProducts/protocol/openid-connect/certs

server:
  servlet:
    contextPath: /v1

feign:
  okhttp:
    enabled: true
  client:
    product:
      url: http://challenge-api.luizalabs.com/api/product
